services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        TheRat\LinodeBundle\Aware\LinodeClientAwareInterface:
            public: true
            calls:
                - [setLinodeClient, ['@TheRat\LinodeBundle\LinodeClient']]

    TheRat\LinodeBundle\:
        resource: '../../*'
        exclude: '../../{Tests,Aware,Message,Model}'

    TheRat\LinodeBundle\MessageHandler\:
        resource: '../../MessageHandler/'
        tags:
            - {name: messenger.message_handler}
            - { name: monolog.logger, channel: 'linode' }

    TheRat\LinodeBundle\LinodeClient:
        public: true
